repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe  # needed for parsing CFN
      - id: end-of-file-fixer
        exclude: .*\.json-result
      - id: file-contents-sorter
        files: |
          (?x)^(
            \.gitignore
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        files: |
          (?x)^(
            \.vscode/(?!cspell).*\.json
          )$
        name: Pretty Format Json (indent=4)
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
        files: |
          (?x)^(
            (.*)?(cdk|tsconfig|tslint).json
          )$
        name: Pretty Format Json (indent=2)
      - id: trailing-whitespace
  - repo: https://github.com/ITProKyle/pre-commit-hook-yamlfmt
    rev: v0.2.0
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --offset, '2', --sequence, '4']
        files: |
          (?x)^(
            \.github/(?!dependabot).*\.(yaml|yml)|
            \.markdownlint.yml|
            \.pre-commit-config.yaml|
          )$
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-toc
  # markdownlint is still used after formatting to enforce some rules that the
  # formatter will break depending on various factors
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
