name: on push

on:
  pull_request:  # any pull request
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: '20'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0  # cspell:ignore ludeeus
        with:
          scandir: ./scripts
  spellcheck:
    # There is an official action published by cSpell.
    # v1.1.1 was tested but did not function as desired so we are using the CLI.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: make spellcheck
  test-local-action-miss:
    name: Test Local Action With Cache Miss
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - id: local-action
        uses: ./
        with:
          python-version: ${{ matrix.python-version }}
      - name: check outputs.python-version
        env:
          MATRIX_PYTHON_VERSION: ${{ matrix.python-version }}
          OUTPUTS_PYTHON_VERSION: ${{ steps.local-action.outputs.python-version }}
        if: '!startsWith(steps.local-action.outputs.python-version, matrix.python-version)'
        run: |
          echo "outputs.python-version=${OUTPUTS_PYTHON_VERSION}"
          echo "matrix.python-version=${MATRIX_PYTHON_VERSION}"
          exit 1
      - name: check outputs.cache-hit (miss)
        env:
          CACHE_HIT_VALUE: ${{ steps.local-action.outputs.cache-hit }}
        if: steps.local-action.outputs.cache-hit == 'true'
        run: |
          echo "outputs.cache-hit=${CACHE_HIT_VALUE}"
          exit 1
      - name: check poetry
        run: poetry --version
      - name: ensure pre-commit is installed
        run: poetry run pre-commit sample-config
  test-local-action-hit:
    # This has to be run after the miss as the cache is not uploaded until the
    # the job is finished.
    name: Test Local Action With Cache Hit
    needs: test-local-action-miss
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - id: local-action
        uses: ./
        with:
          poetry-install: false
          python-version: ${{ matrix.python-version }}
      - name: check outputs.cache-hit (hit)
        env:
          CACHE_HIT_VALUE: ${{ steps.local-action.outputs.cache-hit }}
        if: steps.local-action.outputs.cache-hit != 'true'
        run: |
          echo "outputs.cache-hit=${CACHE_HIT_VALUE}"
          exit 1
      - name: ensure pre-commit is installed
        run: poetry run pre-commit sample-config
  test-local-action-python-version-file:
    name: Test Local Action Using Version From File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: local-action
        uses: ./
        with:
          poetry-install: false
      - name: ensure python version
        run: python -c "import sys; assert sys.version_info >= (3, 12);"
